accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
  path('signup/', SignUpView.as_view(), name='signup'),
]

articles/urls.py
from django.urls import path

from . import views

urlpatterns = [
  # path('main/', views.MainArticlesListView.as_view(), name="main_list"),
  path('sports/', views.SportsArticleListView.as_view(), name="sports_list"),
  path('social/', views.SocialArticleListView.as_view(), name="social_list"),
  path('entertainment/', views.EntertainmentArticleListView.as_view(), name="enternainment_list"),

  path('', views.ArticleListView.as_view(), name="articles"),
  path('new/', views.ArticlesCreateView.as_view(), name="new-article"),
  path('<int:pk>/', views.ArticleDetailView.as_view(), name='article_detail'),
  path('update/<int:pk>', views.ArticleUpdateView.as_view(), name='update-article'),
  path('delete/<int:pk>', views.ArticleDeleteView.as_view(), name='delete-article'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import urls



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('django.contrib.auth.urls')), #import all the paths
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
]

pages/urls.py
from django.urls import path
from .views import HomePageView, AboutPageView

urlpatterns = [
  path('', HomePageView.as_view(), name="home"),
  path('about/', AboutPageView.as_view(), name="about")
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

#AbstractUser has methods to use when extends
class Role(models.Model):
  name = models.CharField(max_length=128)
  description = models.TextField()

  def __str__(self):
    return self.name

class Language(models.Model):
  key = models.CharField(max_length=4)
  name = models.CharField(max_length=128)

  def __str__(self):
    return self.name

# Create your models here.
class CustomUser(AbstractUser):
  role = models.ForeignKey(
    Role,
    on_delete=models.CASCADE,
    blank=True,
    null = True)
  preferred_language = models.ForeignKey(
    Language,
    on_delete=models.CASCADE,
    null=True,
    blank=True,
    default=None
  )

  # def __str__(self):
  #   return

articles/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

# Create your models here.
class Section(models.Model):
  name = models.CharField(max_length=128)
  description = models.TextField()

  def __str__(self):
    return self.name

class Article(models.Model):
  title = models.CharField(max_length=256)
  author = models.ForeignKey(
    get_user_model(),
    on_delete=models.CASCADE)
  section = models.ForeignKey(
    Section,
    on_delete=models.CASCADE,
    null=True,
    blank=True
  )
  body = models.TextField()
  created_on = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return str(self.id) + ' - ' + self.title + ' - ' + str(self.author) + ' - ' + self.body

  def get_absolute_url(self):
    return reverse('article_detail', args=[self.id])

pages/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
  class Meta(UserCreationForm):
    model = CustomUser
    fields = UserCreationForm.Meta.fields + ('role', 'preferred_language')

class CustomUserChangeForm(UserChangeForm):
  class Meta(UserChangeForm):
      model = CustomUser
      fields = UserChangeForm.Meta.fields

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
# from django.contrib.auth.forms import UserCreationForm
# from django.urls import reverse_lazy
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy #wait db its completed


class SignUpView(CreateView):
  form_class = CustomUserCreationForm
  template_name = "registration/signup.html"
  success_url = reverse_lazy("login")

articles/views.py
from distutils.log import Log
from django.shortcuts import render
from django.urls import reverse_lazy

from django.views.generic import (
  ListView,
  DetailView
)

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from .models import Article


class ArticleListView(ListView):
    model = Article
    template_name = "articles/list.html"


# class MainArticlesListView(ArticleListView):

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context["post_list"] = Article.objects.filter(
#             section="1).order_by("created_on").reverse()

class SportsArticleListView(ArticleListView):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_list"] = Article.objects.filter(
        section=1).order_by("created_on").reverse()
        context['section']= "Sports"
        return context

class SocialArticleListView(ArticleListView):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_list"] = Article.objects.filter(
        section=2).order_by("created_on").reverse()
        context['section']= "Social"

        return context

class EntertainmentArticleListView(ArticleListView):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_list"] = Article.objects.filter(
        section=3).order_by("created_on").reverse()
        context['section']= "Entertainment"

        return context

class ArticleDetailView(LoginRequiredMixin,DetailView):
    model = Article
    template_name = "articles/detail.html"
    fields = ['title', 'section', 'body']


class ArticlesCreateView(LoginRequiredMixin,UserPassesTestMixin,CreateView):
    model = Article
    template_name = "articles/new.html"
    fields = '__all__'
    success_url = reverse_lazy('articles')

    def test_func(self):
        print('********** ',self.request.user.role.id)
        return self.request.user.role.id > 1

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class ArticleUpdateView(LoginRequiredMixin, UserPassesTestMixin,UpdateView):
    model = Article
    template_name = "articles/update.html"
    fields = '__all__'
    # success_url = reverse_lazy('articles')

    def test_func(self):
        if self.request.user.role.id > 1:
            article = self.get_object()
            return article.author == self.request.user
        return False

class ArticleDeleteView(DeleteView):
    model = Article
    template_name = "articles/delete.html"
    success_url = reverse_lazy('articles')

    def test_func(self):
        if self.request.user.role.id > 1:
            article = self.get_object()
            return article.author == self.request.user
        return False

pages/views.py
from django.shortcuts import render

from django.views.generic import TemplateView

class HomePageView(TemplateView):
  template_name = "pages/home.html"


class AboutPageView(TemplateView):
    template_name = "pages/about.html"

# Create your views here.

templates/articles/delete.html
{% extends 'base.html'%}

{% block title %} <h1>Delete Article</h1> {% endblock title %}

{% block content %}
  <form method="POST">
    {% csrf_token %}
    <p>Are you sure want to delete article "{{object.title}}" ?</p>
    <button type="submit" class="btn-confirm">Confirm</button>
  </form>
{% endblock content %}

templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}{{ article.title }}{% endblock title%}

{% block content %}
  <h1>{{ article.title }}</h1>
  <div class="detail-container">
    <small>By {{ article.author }} | on: {{ article.created_on }}</small>

    <p class="my-3">{{ article.body }}</p>
    {% if user.is_authenticated %}

    <div class="row">
      <div class="col-md-3">
        <a href="{% url 'update-article' article.id %}" class="btn btn-edit" style="width:80%">Edit</a>
      </div>

      <div class="col-md-3">
        <a href="{% url 'delete-article' article.id %}" class="btn btn-delete" style="width:80%">Delete</a>
      </div>
    </div>
  </div>

  {% endif %}
{% endblock content %}


templates/articles/list.html
{% extends 'base.html' %}

{% block title%} Articles {% endblock title%}

{% block content%}
    <h1 style="text-align: center;"> {{section}} articles </h1>
    <!-- <h2> {{section}} </h2> -->
    <!-- <h3></h3> -->
    <ul>
      {% for article in post_list %}
        <!-- <li>{{article.title}}</li> -->
        {% if user.is_authenticated %}
        <li>
          <a href="{% url 'article_detail' article.id%}" style="color: #764a2a;">{{article.title}}</a>
        </li>
        {%endif%}
      {% endfor %}
    </ul>


  <!-- {% for article in article_list %}
  <div class="card mb-3 card-style" style="width: 100%; background-color: transparent;">
    <div class="card-body">
      <h5 class="card-title">{{article.title}}</h5>
      <h6 class="card-subtitle mb-2 text-muted">Author: {{article.author}}</h6>
        <p class="card-text">Note: {{article.body}}</p>
        <a href="{% url 'update-article' article.id %}" class="btn btn-confirm " style="width:45%">Update</a>
        <a href="{% url 'delete-article' article.id %}" class="btn btn-delete" style="width:45%">Delete</a>
      </div>
    </div>
    {% empty %}
    <h2>There's not Articles yet</h2>
    {% endfor %} -->
  </div>
{% endblock content%}

templates/articles/new.html
{% extends 'base.html' %}

{% block title %} New article {% endblock title%}


{% block content %}
  <form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-confirm">Create new article</button>
  </form>
{% endblock content %}



templates/articles/update.html
{% extends 'base.html' %}

{% block title %}Update{% endblock title %}

{% block content %}
  <form method="POST">
    {{form.as_p}}
    {% csrf_token %}
    <input type="submit" value="Update">
  </form>
{% endblock content %}s

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title%} {% endblock title%}</title>
    <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
  <div class="main-container">
    <div>
      <!-- <img src="{% static 'img/camera.png' %}" alt="" width="10%" height="20%"> -->
      <h1 class="main-title">NewsPaper the Hero</h1>
    </div>
    <nav class="navbar navbar-expand-lg mt-4 navbar-style">
      <div class="container-fluid ">
        <!-- <a class="navbar-brand" href="{% url 'home' %}">JUNE 2022</a> -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarNav">
          <ul class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
              <a class="nav-link active" aria-current="page" href="{% url 'about' %}">About</a>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Articles
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'articles' %}">See all articles</a></li>
                  <li><a class="dropdown-item" href="{% url 'new-article' %}">Create new article</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'password_change' %}">Change password</a>
                <a class="nav-link" href="{% url 'password_reset' %}">Password reset</a>
                <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
              {% else %}
                <a class="nav-link" href="{% url 'login' %}">Log In</a>
                <a class="nav-link" href="{% url 'signup' %}">SignUp</a>
              {% endif %}

          </ul>
        </div>
      </div>
    </nav>
    <div class="container mt-2 mb-3 categories-list">
      <div class="row">
        <div class="col">
          <a href="{% url 'enternainment_list' %}">Entertainment</a>
        </div>
        <div class="col">
          <a href="{% url 'social_list' %}">Social</a>
        </div>
        <div class="col">
          <a href="{% url 'sports_list' %}">Sports</a>
        </div>
      </div>
    </div>
    <!-- <div style="width: 40%;" class="mt-2 mb-5">
      <ul style="display:flex; justify-content: space-between;" >
        <a style="color: gray;" href="{% url 'enternainment_list' %}">Entertainment</a> |
        <a style="color: gray;" href="{% url 'social_list' %}">Social</a> |
        <a style="color: gray;" href="{% url 'sports_list' %}">Sports</a>
      </ul>
    </div> -->

    <div class="container">
      {% block content %}
      {% endblock content %}
    </div>
  </div>

  <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

templates/pages/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock title %}

{% block content %}
  <div class="container">
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore ex atque assumenda, et eligendi voluptatem mollitia repudiandae, optio minus ea veritatis natus dolor dicta officiis nulla itaque, temporibus iste officia expedita. Pariatur quasi temporibus optio commodi, natus hic nemo ducimus dolor sapiente itaque possimus qui deleniti accusantium nesciunt ipsa ex doloribus incidunt amet aliquid maiores sint, unde est? Commodi, distinctio.</h1>
    <br>
    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nam excepturi dolorem vel natus mollitia? Doloremque praesentium quia incidunt officia? Quis culpa obcaecati, numquam provident a officiis nemo corporis deserunt accusantium recusandae dolores iure id dolorem, commodi dolor iusto itaque neque omnis. Nulla, iste et aut aspernatur iusto dicta vel deleniti animi mollitia eos cum modi delectus quam voluptates recusandae laudantium inventore vitae ipsam ad amet deserunt, neque molestiae doloribus sint? Aspernatur, quas ipsum ab laborum esse numquam corporis totam error assumenda, placeat iure magni enim. Earum assumenda ipsum ab corrupti, blanditiis fugiat, modi, impedit sunt sequi provident ullam iste! Vitae accusamus repudiandae ratione vel tempore, est itaque tenetur officia id, aut animi ea dolor praesentium quasi consequatur libero. Culpa consectetur iste aut veritatis deserunt, qui perferendis modi? Voluptates ab, itaque dolorem est voluptatem optio quasi quos illum neque eius maiores ea aliquam, natus exercitationem. Sint repudiandae eum illo voluptatem, pariatur commodi recusandae saepe beatae perferendis perspiciatis? Ipsum possimus saepe dolor suscipit dolore at ut, incidunt ad nesciunt totam voluptatem obcaecati a tempore eum reprehenderit tempora placeat. Doloribus ipsum impedit aperiam accusantium soluta ipsa ducimus quia vero, a deleniti provident illo quae, culpa quo ipsam, nobis odio quidem eum? Nam, voluptatem.</p>
  </div>
{% endblock content %}

templates/pages/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block content %}
<h1 class="mb-4" style="text-align: center">Where is Batman?</h1>
<div class="container ">
  <div class="row">
    <div class="col-7 justify-content-center first-column-home">
      <img class="batman1-img"  src="{% static 'img/batman.png' %}" alt=""  width="50%">
      <span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis tempora voluptatibus quasi illo provident adipisci nobis nam alias unde laudantium dolores ipsum beatae quos ipsam modi laboriosam eius quaerat quis voluptates rerum, id nulla aliquam, quae eos. Ratione quasi repudiandae dicta possimus nisi. Animi porro ipsum distinctio excepturi, eveniet minima quae sunt fugit. Facere at voluptas cupiditate commodi reiciendis veniam accusamus quibusdam. Eaque alias quas beatae dolor aut laudantium illo id error soluta fugit totam, harum ut qui voluptatum, deleniti corrupti facilis quaerat culpa maiores! Quas illum maxime nam natus modi aut unde repudiandae alias quaerat debitis explicabo, veniam suscipit.</sp>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsum natus quod accusantium facilis sed fuga recusandae esse doloribus ea voluptate eius iure autem, vel saepe voluptates modi eligendi totam quaerat?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsum natus quod accusantium facilis sed fuga recusandae esse doloribus ea voluptate eius iure autem, vel saepe voluptates modi eligendi totam quaerat?</p>
      </div>
    <div class="col-5 justify-content-center second-column-home">
      <h3 style="border-top: 1px solid #000;border-bottom: 1px solid #000">Hero Stadium. <br> The Batman's band!</h3>
      <br>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis tempora voluptatibus quasi illo provident adipisci nobis nam alias unde laudantium dolores ipsum beatae quos ipsam modi laboriosam eius quaerat quis voluptates rerum, id nulla aliquam, quae eos. Ratione quasi repudiandae dicta possimus nisi. Animi porro ipsum distinctio excepturi, eveniet minima quae sunt fugit. Facere at voluptas cupiditate commodi reiciendis veniam accusamus quibusdam. Eaque alias quas beatae dolor aut laudantium illo id error soluta fugit totam, harum ut qui voluptatum, deleniti corrupti facilis quaerat culpa maiores! Quas illum maxime nam natus modi aut unde repudiandae alias quaerat debitis explicabo, veniam suscipit.</p>
    </div>
    <!-- <div class="col-3 justify-content-center">
      Column
    </div> -->
  </div>
</div>
{% endblock content %}